# Generated by Django 4.0.4 on 2022-06-05 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('fecha_fabricacion', models.DateField()),
                ('caducado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='medicamentocompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fichapaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamento')),
            ],
        ),
    ]
