# Generated by Django 3.1 on 2022-06-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220612_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='medicamentos'),
        ),
        migrations.AddField(
            model_name='medicamentocompra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='listacompra'),
        ),
    ]
